IERSystem/IERSystem/Areas/Administrator/Models/SoKQThuNghiem.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IERSystem.Areas.Administrator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoKQThuNghiem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoKQThuNghiem()
        {
            this.KQThuNghiemMaus = new HashSet<KQThuNghiemMau>();
        }
    
        public long Id { get; set; }
        public string MaMau { get; set; }
        public System.DateTime NgayNhanMau { get; set; }
        public System.DateTime NgayTraMau { get; set; }
        public System.DateTime NgayThemVaoSo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KQThuNghiemMau> KQThuNghiemMaus { get; set; }
        public virtual MauLayHienTruong MauLayHienTruong { get; set; }
        public virtual FormKQ FormKQ { get; set; }
    }
}

IERSystem/IERSystem/Areas/Administrator/Controllers/SoKQThuNghiemController.cs
using System;
using System.Collections.Generic;
//using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IERSystem.Areas.Administrator.Models;

namespace IERSystem.Areas.Administrator.Controllers
{
    public class SoKQThuNghiemController : Controller
    {
        private IERSystemModelContainer db = new IERSystemModelContainer();

        // GET: /Administrator/SoKQThuNghiem/
        public async Task<ActionResult> Index()
        {
            return View(await db.SoKQThuNghiems.ToListAsync());
        }

        // GET: /Administrator/SoKQThuNghiem/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SoKQThuNghiem sokqthunghiem = await db.SoKQThuNghiems.FindAsync(id);
            if (sokqthunghiem == null)
            {
                return HttpNotFound();
            }
            return View(sokqthunghiem);
        }

        // GET: /Administrator/SoKQThuNghiem/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Administrator/SoKQThuNghiem/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include="Id,KyHieuMau,NgayNhanMau,NgayTraMau")] SoKQThuNghiem sokqthunghiem)
        {
            if (ModelState.IsValid)
            {
                db.SoKQThuNghiems.Add(sokqthunghiem);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(sokqthunghiem);
        }

        // GET: /Administrator/SoKQThuNghiem/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SoKQThuNghiem sokqthunghiem = await db.SoKQThuNghiems.FindAsync(id);
            if (sokqthunghiem == null)
            {
                return HttpNotFound();
            }
            return View(sokqthunghiem);
        }

        // POST: /Administrator/SoKQThuNghiem/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include="Id,KyHieuMau,NgayNhanMau,NgayTraMau")] SoKQThuNghiem sokqthunghiem)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sokqthunghiem).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(sokqthunghiem);
        }

        // GET: /Administrator/SoKQThuNghiem/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SoKQThuNghiem sokqthunghiem = await db.SoKQThuNghiems.FindAsync(id);
            if (sokqthunghiem == null)
            {
                return HttpNotFound();
            }
            return View(sokqthunghiem);
        }

        // POST: /Administrator/SoKQThuNghiem/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            SoKQThuNghiem sokqthunghiem = await db.SoKQThuNghiems.FindAsync(id);
            db.SoKQThuNghiems.Remove(sokqthunghiem);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IERSystem/IERSystem/Areas/QuanLyKetQuaPhanTich/Controllers/SoKQThuNghiemController.cs
using IERSystem.Areas.Administrator.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using IERSystem.Areas.QuanLyKetQuaPhanTich.Models;
using IERSystem.BusinessLogic.TableForms;
using IERSystem.BusinessLogic.Utils;

namespace IERSystem.Areas.QuanLyKetQuaPhanTich.Controllers
{
    public class SoKQThuNghiemController : Controller
    {
        private IERSystemModelContainer db = new IERSystemModelContainer();

        // GET: QuanLyKetQuaPhanTich/SoKQThuNghiem
        public async Task<ActionResult> Index()
        {
            return View(await db.SoKQThuNghiems.ToListAsync());
        }

        // GET: QuanLyKetQuaPhanTich/SoKQThuNghiem/Details/5
        public ActionResult Details(int id)
        {
            var sokq = db.SoKQThuNghiems.Find(id);
            if (sokq == null)
            {
                return HttpNotFound();
            }
            return View(new FormKQOutputModel() { 
                MaKhachHang = sokq.MauLayHienTruong.PhieuYeuCau.MaDon,
                MaMau = sokq.MauLayHienTruong.MaMau,
                NgayGuiMau = sokq.MauLayHienTruong.PhieuYeuCau.NgayLayMau.ToShortDateString(),
                NoiLayMau = sokq.MauLayHienTruong.PhieuYeuCau.DiaChiLayMau,
                ViTriLayMau = sokq.MauLayHienTruong.PhieuYeuCau.NoiLayMau,
                LoaiMau = LoaiMauConverter.ToLoaiMau(sokq.MaMau),
                DiaChi = sokq.MauLayHienTruong.PhieuYeuCau.DiaChiKhachHang,
                ChiTieuPhanTichKQs = sokq.KQThuNghiemMaus.Select((kqtn) =>
                {
                    return new ChiTieuPTDetailsModel()
                    {
                        DonVi = kqtn.DonVi,
                        GiaTri = kqtn.KetQua,
                        NguoiThucHien = "N/A",
                        PhuongPhap = kqtn.ChiTieuPhanTich.TenPhuongPhap,
                        TenChiTieu = kqtn.ChiTieuPhanTich.TenChiTieu
                    };
                })
            });
        }

        // GET: QuanLyKetQuaPhanTich/SoKQThuNghiem/Create
        public ActionResult Create()
        {
            return View(MauLayHienTruongAPIImpl.GetMauPTDaChuyen(db));
        }

        // POST: QuanLyKetQuaPhanTich/SoKQThuNghiem/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: QuanLyKetQuaPhanTich/SoKQThuNghiem/Edit/5
        public ActionResult Edit(long id = 0)
        {
            var sokq = db.SoKQThuNghiems.Find(id);
            if (sokq == null)
            {
                return HttpNotFound();
            }
            return View(sokq);
        }

        // GET: QuanLyKetQuaPhanTich/SoKQThuNghiem/AddResult/5
        public ActionResult AddResult(long id = 0)
        {
            var sokq = db.SoKQThuNghiems.Find(id);
            if (sokq == null)
            {
                return HttpNotFound();
            }
            return View(sokq);
        }

        // GET: QuanLyKetQuaPhanTich/SoKQThuNghiem/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: QuanLyKetQuaPhanTich/SoKQThuNghiem/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IERSystem/IERSystem/Areas/Administrator/Views/SoKQThuNghiem/Details.cshtml
@model IERSystem.Areas.Administrator.Models.SoKQThuNghiem

@{
    ViewBag.Title = "Chi tiết";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

<h2>Chi tiết kết quả thử nghiệm</h2>

<div>
    <div class="clearfix">
    </div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <dl class="dl-horizontal">
                    <dt>
                        <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">
                            Ký hiệu mẫu
                        </label>
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.KyHieuMau)
                    </dd>

                    <dt>
                        <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">
                            Ngày nhận mẫu
                        </label>
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.NgayNhanMau)
                    </dd>

                    <dt>
                        <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">
                            Ngày trả mẫu
                        </label>
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.NgayTraMau)
                    </dd>

                </dl>
            </div>

            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>
                                KẾT QUẢ THỬ NGHIỆM
                            </h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <li>
                                    <a class="collapse-link">
                                        <i class="fa fa-chevron-up"></i>
                                    </a>
                                </li>
                                @*<li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                            <i class="fa fa-plus"></i>
                                        </a>
                                        <ul class="dropdown-menu" role="menu">
                                            <li>
                                                <a href="@Url.Action("Create", "SoChuyenMau")">Tạo mẫu chuyển mới</a>
                                            </li>
                                            <li>
                                                <a href="#">Settings 2</a>
                                            </li>
                                        </ul>
                                    </li>*@
                                <li>
                                    <a class="close-link">
                                        <i class="fa fa-close"></i>
                                    </a>
                                </li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content" style="display:block;">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th rowspan="4">Mã khách hàng</th>
                                        <th rowspan="4">Mã mẫu</th>
                                        <th rowspan="4">Chỉ tiêu thử nghiệm</th>
                                        <th rowspan="4">Người giao mẫu</th>
                                        <th rowspan="4">Người nhận mẫu</th>
                                        <th rowspan="4">Ngày giao mẫu</th>
                                        <th rowspan="4">Ngày trả kết quả</th>
                                        <th rowspan="4">Điền tên</th>
                                        <th rowspan="4">Ghi chú</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @*@foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.MaKhachHang)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.MaMau)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.ChiTieuThuNghiem)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.NguoiGiaoMau)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.NguoiNhanMau)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.NgayGiaoMau)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.NgayTraKetQua)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.DienTien)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.GhiChu)
                                                </td>
                                            </tr>
                                        }*@
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>

<p class="mid_center">
    <button class="btn btn-warning" data-toggle="tooltip" title="Chỉnh sửa" onclick="location.href='@Url.Action("Edit", "SoKQThuNghiem", new { id = Model.Id })'"><span class="fa fa-edit"></span></button>
    <button class="btn btn-success" data-toggle="tooltip" title="Quay lại" onclick="location.href='@Url.Action("Index", "SoKQThuNghiem", new { id = Model.Id })'"><span class="fa fa-arrow-left"></span></button>
</p>

IERSystem/IERSystem/Areas/Administrator/Views/SoKQThuNghiem/Edit.cshtml
@model IERSystem.Areas.Administrator.Models.SoKQThuNghiem

@{
    ViewBag.Title = "Chỉnh";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

<h2>Chỉnh sửa</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Chỉnh kết quả thử nghiệm</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <br>
                    <form id="demo-form2" data-parsley-validate="" class="form-horizontal form-label-left" novalidate="">
                        @Html.ValidationSummary(true)

                        <div class="form-group">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">
                                Ký hiệu mẫu
                            </label>
                            <div class="col-md-4 col-sm-4 col-xs-12">
                                @Html.TextBoxFor(model => model.KyHieuMau, new { @class = "form-control col-md-4 col-xs-12", @readonly = "readonly" })
                                @Html.ValidationMessageFor(model => model.KyHieuMau)
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">
                                Ngày nhận mẫu
                            </label>
                            <div class="col-md-4 col-sm-4 col-xs-12">
                                @Html.TextBoxFor(model => model.NgayNhanMau, new { @class = "form-control col-md-4 col-xs-12", @readonly = "readonly" })
                                @Html.ValidationMessageFor(model => model.NgayNhanMau)
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">
                                Ngày trả mẫu
                            </label>

                            <div class="col-md-4 col-sm-4 col-xs-12">
                                @Html.TextBoxFor(model => model.NgayTraMau, new { @class = "form-control col-md-4 col-xs-12", @readonly = "readonly" })
                                @Html.ValidationMessageFor(model => model.NgayTraMau)
                            </div>
                        </div>

                        <div class="clearfix"></div>
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <div class="x_panel">
                                    <div class="x_title">
                                        <h2>
                                            DANH SÁCH KẾT QUẢ
                                        </h2>
                                        <ul class="nav navbar-right panel_toolbox">
                                            <li>
                                                <a class="collapse-link">
                                                    <i class="fa fa-chevron-up"></i>
                                                </a>
                                            </li>
                                        </ul>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="x_content" style="display:block;">
                                        <table class="table table-striped">
                                            <thead>
                                                <tr>
                                                    <th>Chỉ tiêu thử nghiệm</th>
                                                    <th>Đơn vị</th>
                                                    <th>Kết quả</th>  
                                                    <th>Người thực hiện</th>                                                    
                                                </tr>
                                            </thead>
                                            <tbody>        
                                                <tr>
                                                    <td>Thử nước</td>
                                                    <td>ml</td>
                                                    <td id="tboxKQ"><input type="email" class="form-control" id="ket-qua" ></td>
                                                    <td>Nguyễn Văn A</td>
                                                    <td><button id="btnSaveKQ" type="button" data-toggle="tooltip" title="Lưu"><span class="fa fa-save"></span></button></td>                                         
                                                </tr>                                                                                   
                                            </tbody>
                                        </table>
                                    </div>

                                </div>
                            </div>
                        </div>                     

                    </form>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Lưu" class="btn btn-success" />
                        <input type="button" class="btn btn-danger" value="Quay lại" onclick="location.href='@Url.Action("Index", "SoKQThuNghiem")'" />
                    </div>
                </div>
            </div>
        </div>
</div>
}

<div>
    @Html.ActionLink("Trở về", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

        <script>
    $(document).ready(function () {

        const $Global = [];

        $('#themKQModal').on('hidden.bs.modal', function () {
            $(this).find("input,textarea,select").val('').end();

        });

        function Delete() {
            var par = $(this).parent().parent(); //tr
            par.remove();
        }

        function OnRowIn() {
            var deleteCell = $(this).children().last();
            deleteCell.html("<a id='deleteRowBtn' href='#'><span class='glyphicon glyphicon-remove'></span></a>");
            $('#deleteRowBtn').bind("click", Delete);
        }

        function OnRowOut() {
            $(this).children().last().html('');
        }

        $("#saveKQBtn").bind("click", function () {
            var tabledata = $("#sampledata-table tbody");

            tabledata.append(
                "<tr>" +
                //"<td></td>" +
                "<td>" + $("#chitieu-thunghiem").val() + "</td>" +
                "<td>" + $("#don-vi").val() + "</td>" +
                "<td>" + $("#ket-qua").val() + "</td>" +
                "<td>" + $("#nguoi-thuchien").val() + "</td>" +
                "<td></td>" +
                "</tr>");

            //On Row Hover
            tabledata.children().last().hover(OnRowIn, OnRowOut);
        });

        $("#submitBtn").bind("click", function () {         

            function getFormData() {
                var res = {
                    TenKhachHang: $("#TenKhachHang").val(),
                    MaSoThue: $("#MaSoThue").val(),
                    TenDaiDien: $("#TenDaiDien").val(),
                    SoDienThoai: $("#SoDienThoai").val(),
                    SoFax: $("#SoFax").val(),
                    DiaChiLayMau: $("#DiaChiLayMau").val(),
                    DiaChiKhachHang: $("#DiaChiKhachHang").val(),
                    NgayTaoHD: $("#NgayTaoHD").val(),
                    NgayDuKienTraMau: $("#NgayTaoHD").val()+$("#NgayDuKienTraMau").val(),
                    PhuongPhapLayMau: $("#PhuongPhapLayMau").val(),
                    TenTieuChuanDoiChieu: $("#TenTieuChuanDoiChieu").val(),
                    PhiThiNghiemTamTinh: $("#PhiThiNghiemTamTinh").val(),
                    TienKhachHangTraTruoc: $("#TienKhachHangTraTruoc").val()
                };
                var sampledata = $("#sampledata-table tbody tr").map(function (i, elem) {
                    var rowdata = $(elem).find("td").map(function () { return $(this).text(); }).get();
                    //alert(rowdata);
                    return {
                        MaMauKH: rowdata[0],
                        //Get the first 2 characters of Kí Hiệu Mẫu
                        KiHieuMau: rowdata[1].slice(0, 2),
                        ViTriLayMau: rowdata[2],
                        SoLuong:  $Global[i].SoLuong,
                        DonVi:  $Global[i].DonVi,
                        MoTaMau: rowdata[4],
                        ChiTieuPhanTich: rowdata[5]
                    }
                }).get();
                res.MauLayHienTruongs = sampledata;
                console.log(res);
                return res;
            }
            var formData = getFormData();
            $.ajax({
                type: 'POST',
                url: ' @Url.Action("Create", "API")',
                data: JSON.stringify(formData),
                success: function (res) {
                   if (res.isOk) {
                      console.log(formData);
                   } else {
                      console.log(res.errMsg);
                   }
                   location.href = '@Url.Action("Index", "YeuCauLayMau")'
                },
                dataType: 'json',
                contentType: 'application/json; charset=utf-8'
            });
        });
    });
        </script>

    @*<script>
        $(document).ready(function () {
            $('#NgayNhanMau').daterangepicker({
                singleDatePicker: true,
                calender_style: "picker_1"
            }, function (start, end, label) {
                console.log(start.toISOString(), end.toISOString(), label);
            });
        });
    </script>

    <script>
        $(document).ready(function () {
            $('#NgayTraMau').daterangepicker({
                singleDatePicker: true,
                calender_style: "picker_1"
            }, function (start, end, label) {
                console.log(start.toISOString(), end.toISOString(), label);
            });
        });
    </script>*@
}