IERSystem/IERSystem/Areas/BaoGiaChiTieu/Controllers/MauBaoGiaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IERSystem.BusinessLogic;
using IERSystem.Areas.Administrator.Models;
using IERSystem.BusinessLogic.TableForms;

namespace IERSystem.Areas.BaoGiaChiTieu.Controllers
{
    public class MauBaoGiaController : Controller
    {
        private IERSystemModelContainer db = new IERSystemModelContainer();

        // GET: BaoGiaChiTieu/BaoGiaChiTieu/Upload
        public ActionResult Upload(FormCollection form_collection)
        {
            if (Request != null) {
                HttpPostedFileBase file = Request.Files["UploadedFile"];
                ChiTieuPhanTichAPIImpl.Create(file, db);
                db.SaveChanges();
            }
            return View("Upload");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IERSystem/IERSystem/Areas/BaoGiaChiTieu/Views/MauBaoGia/Upload.cshtml
@{
    ViewBag.Title = "Upload";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("Upload", "MauBaoGia", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="file" name="UploadedFile" />
    <input type="submit" name="Submit" id="Submit" value="Upload" />
}
<!-- page content -->]
@*@<div class="">
=======
@*<div class="">
>>>>>>> master
    <div class="page-title">
        <div class="title_left">
            <h3>Upload chỉ tiêu phân tích </h3>
        </div>
        <div class="title_right">
            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">Go!</button>
                    </span>
                </div>
            </div>
        </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Tải lên file</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li>
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li>
                            <a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <p>Kéo thả hoặc nhấp vào đây để upload file.</p>
                    <form action="form_upload.html" class="dropzone" name="UploadedFile"></form>
                    <br />
                    <br />
                    <br />
                    <br />
                </div>
            </div>
        </div>
    </div>
<<<<<<< HEAD
</div>
<!-- /page content -->
*@