IERSystem/IERSystem/Areas/Administrator/Models/CacSoChuyenMau.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IERSystem.Areas.Administrator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CacSoChuyenMau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CacSoChuyenMau()
        {
            this.SoChuyenMaus = new HashSet<SoChuyenMau>();
        }
    
        public long Id { get; set; }
        public System.DateTime TuNgay { get; set; }
        public System.DateTime DenNgay { get; set; }
        public long UserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoChuyenMau> SoChuyenMaus { get; set; }
        public virtual User CreatedBy { get; set; }
    }
}

IERSystem/IERSystem/Areas/Administrator/Controllers/CacSoChuyenMauController.cs
using System;
using System.Collections.Generic;
//using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IERSystem.Areas.Administrator.Models;

namespace IERSystem.Areas.Administrator.Controllers
{
    public class CacSoChuyenMauController : Controller
    {
        private IERSystemModelContainer db = new IERSystemModelContainer();

        // GET: /Administrator/CacSoChuyenMau/
        public async Task<ActionResult> Index()
        {
            return View(await db.CacSoChuyenMaus.ToListAsync());
        }

        // GET: /Administrator/CacSoChuyenMau/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CacSoChuyenMau cacsochuyenmau = await db.CacSoChuyenMaus.FindAsync(id);
            if (cacsochuyenmau == null)
            {
                return HttpNotFound();
            }
            return View(cacsochuyenmau);
        }

        // GET: /Administrator/CacSoChuyenMau/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Administrator/CacSoChuyenMau/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include="Id,Year")] CacSoChuyenMau cacsochuyenmau)
        {
            if (ModelState.IsValid)
            {
                cacsochuyenmau.CreatedBy = db.Users.Find((int)Session["loggedID"]);
                cacsochuyenmau.CreatedDate = DateTime.Now;
                db.CacSoChuyenMaus.Add(cacsochuyenmau);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(cacsochuyenmau);
        }

        // GET: /Administrator/CacSoChuyenMau/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CacSoChuyenMau cacsochuyenmau = await db.CacSoChuyenMaus.FindAsync(id);
            if (cacsochuyenmau == null)
            {
                return HttpNotFound();
            }
            return View(cacsochuyenmau);
        }

        // POST: /Administrator/CacSoChuyenMau/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include="Id,Year")] CacSoChuyenMau cacsochuyenmau)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cacsochuyenmau).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(cacsochuyenmau);
        }

        // GET: /Administrator/CacSoChuyenMau/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CacSoChuyenMau cacsochuyenmau = await db.CacSoChuyenMaus.FindAsync(id);
            if (cacsochuyenmau == null)
            {
                return HttpNotFound();
            }
            return View(cacsochuyenmau);
        }

        // POST: /Administrator/CacSoChuyenMau/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            CacSoChuyenMau cacsochuyenmau = await db.CacSoChuyenMaus.FindAsync(id);
            db.CacSoChuyenMaus.Remove(cacsochuyenmau);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IERSystem/IERSystem/Areas/QuanLySoChuyenMau/Controllers/CacSoChuyenMauController.cs
using IERSystem.Areas.Administrator.Models;
using IERSystem.Areas.QuanLySoChuyenMau.Models;
using IERSystem.BusinessLogic.TableForms;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace IERSystem.Areas.QuanLySoChuyenMau.Controllers
{
    public class CacSoChuyenMauController : Controller
    {
        private IERSystemModelContainer db = new IERSystemModelContainer();

        // GET: QuanLySoChuyenMau/CacSoChuyenMau
        public async Task<ActionResult> Index()
        {
            return View(await CacSoChuyenMauAPIImpl.CreateView(db));
        }

        // POST: /QuanLyCacSoChuyenMau/CacSoChuyenMau/Create
        public ActionResult Create([Bind(Include = "Name,TuThang,DenThang")]SoChuyenMauCreateInputModel cacsochuyenmau_inp)
        {
            if (ModelState.IsValid)
            {
                var today = DateTime.Now;
                cacsochuyenmau_inp.CreatedBy = db.Users.Find((long)Session["loggedID"]);
                cacsochuyenmau_inp.CreatedDate = DateTime.Now;
                cacsochuyenmau_inp.Nam = today.Year;
                cacsochuyenmau_inp.TuThang = today.Month;
                cacsochuyenmau_inp.DenThang = today.Month;
            }
            return View(cacsochuyenmau_inp);
        }

        // GET: /Administrator/SoChuyenMau/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SoChuyenMau sochuyenmau = await db.SoChuyenMaus.FindAsync(id);
            if (sochuyenmau == null)
            {
                return HttpNotFound();
            }
            return View(sochuyenmau);
        }

        // POST: /Administrator/SoChuyenMau/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,MaKhachHang,MaMau,ChiTieuThuNghiem,NguoiGiaoMau,NguoiNhanMau,NgayGiaoMau,NgayTraKetQua,DienTien,GhiChu")] SoChuyenMau sochuyenmau)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sochuyenmau).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(sochuyenmau);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IERSystem/IERSystem/Areas/QuanLySoChuyenMau/Views/CacSoChuyenMau/Create.cshtml
@model IERSystem.Areas.QuanLySoChuyenMau.Models.SoChuyenMauCreateInputModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

<h2>Tạo sổ chuyển mẫu</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Tạo sổ nhận mới</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <br>
                    <form id="demo-form2" data-parsley-validate="" class="form-horizontal form-label-left" novalidate="">
                        @Html.ValidationSummary(true)

                        <div class="form-group">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">
                                Năm<span class="required">*</span>
                            </label>
                            <div class="col-md-4 col-sm-4 col-xs-12">
                                @Html.TextBoxFor(model => model.Nam, new { @class = "form-control col-md-4 col-xs-12", required = "required" })
                                @Html.ValidationMessageFor(model => model.Nam)
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">
                                Từ tháng<span class="required">*</span>
                            </label>
                            <div class="col-md-4 col-sm-4 col-xs-12">
                                @Html.TextBoxFor(model => model.TuThang, new { @class = "form-control col-md-4 col-xs-12", required = "required" })
                                @Html.ValidationMessageFor(model => model.TuThang)
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">
                                Đến tháng<span class="required">*</span>
                            </label>
                            <div class="col-md-4 col-sm-4 col-xs-12">
                                @Html.TextBoxFor(model => model.DenThang, new { @class = "form-control col-md-4 col-xs-12", required = "required" })
                                @Html.ValidationMessageFor(model => model.DenThang)
                            </div>
                        </div>
                    </form>


                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="button" id="submitBtn" value="Tạo" class="btn btn-success" />
                            <input type="button" class="btn btn-danger" value="Quay lại" onclick="location.href='@Url.Action("Index", "CacSoNhanMau")'" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script>
    $("#submitBtn").bind("click", function () {
        formData = {
            Nam: $("#Nam").val(),
            TuThang: $("#TuThang").val(),
            DenThang: $("#DenThang").val()
        };
        $.ajax({
            type: 'POST',
            url: ' @Url.Action("Create", "API")',
            data: JSON.stringify(formData),
            success: function (res) {
                if (res.IsOK) {
                    new PNotify({
                        title: 'Tạo sổ thành công',
                        text: 'tạo sổ mới hợp lệ, sổ đã được thêm vào lưu trữ',
                        type: 'success',
                        styling: 'bootstrap3'
                    });
                    setTimeout(function () {
                        window.location.href = '@Url.Action("Index", "CacSoChuyenMau")'
                    }, 1500);
                } else {
                    new PNotify({
                        title: 'Tạo sổ thất bại',
                        text: 'hãy kiểm tra lại tính hợp lệ của thông tin (tháng từ 1-12, năm dương).',
                        type: 'error',
                        styling: 'bootstrap3'
                    });
                }
            },
            dataType: 'json',
            contentType: 'application/json; charset=utf-8'
        });
    });

    </script>
    }